### ISSUE TITLE
Table overwritten

### ISSUE THREAD

**Issue by dashaw92** [hbh7/Python-Todo-List#1]
https://github.com/hbh7/Python-Todo-List/blob/master/todo.py#L92

``` sql
create table todoList (
 task text,
 priority int,
 completed bool)
```

Fixed:

``` sql
CREATE TABLE IF NOT EXISTS todoList (
  task text,
  priority int,
  completed bool
)
```

**Comment by hbh7** [comment]
I've never actually had a problem with it overwriting data. That's what that function is for. If it works, then the table didn't exist. If it doesn't work, then the table is there. I suppose that is likely a better solution though.
